controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - SOLID001_link_joint
        - ZahnradGross003_link_joint
        - ZahnradGross004_link_joint
